#!/bin/bash

/usr/sbin/munin-node-configure --shell 2>/dev/null | grep memcached_multi_ | sh

(echo "[memcached_multi_*]"; echo "env.host 127.0.0.1 env.port 11211 env.timescale 3") > /etc/munin/plugin-conf.d/memcached_multi_

/etc/init.d/munin-node restart

