#!/bin/bash

PLUGINS="items memory bytes conns commands evictions"

for p in $PLUGINS; do
	ln -vsf  /usr/share/munin/plugins/memcached_ /etc/munin/plugins/memcached_$p
done

(echo "[memcached_*]"; echo "env.host 127.0.0.1 env.port 11211 env.timescale 3") > /etc/munin/plugin-conf.d/memcached

/etc/init.d/munin-node restart

